title: <p align="center"> Andy Putratama </p>

logo: "/image/image_round.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/andyptr/">LinkedIn</a> |
  <a href="https://github.com/andyptr">GitHub</a>
  </p>
  
  <p align="justify">
  I am a power system researcher in the G2ELab, France.
  <br><br>
  My research area area power systems modeling, operational management & design, and energy markets.
  <br><br>
  </p>
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
