title: <p align="center"> Andy Putratama </p>

logo: "/image/image_round.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/andyptr/">LinkedIn</a> |
  <a href="https://github.com/andyptr">GitHub</a>
  </p>
  
  <p align="justify">
  I am currently a power system researcher at the G2ELab, France.  My research interests mainly focus on distribution grid / microgrid operational planning and modelling, including distributed and peer-to-peer control, voltage control, and local energy markets.
  </p>
show_downloads: false
google_analytics: 297362505
theme: jekyll-theme-minimal
